config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, only: [:index, :show]
  resource :cart, only: [:show]
  resources :orders, only: [:create, :update, :destroy]
  post '/orders/:id',  to: 'orders#create', as: "order_items"
  post '/orders/:id',  to: 'orders#update', as: "order_item"
  get '/category/:id',  to: 'product_categories#show', as: "category"
  get '/about',  to: 'home#about', as: "about"
  get '/contact_us',  to: 'home#contact_us', as: "contact_us"
  get '/orders/checkout', to: 'orders#checkout', as: "checkout"
  get '/order/placed', to: 'orders#post_checkout', as: "post_checkout"
  get 'all_products', to: 'products#all_products', as: "all_products"
  get 'featured_products', to: 'products#featured_products', as: "featured_products"
  get 'recent_products', to: 'products#recent_products', as: "recent_products"
  resources :payments
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # if current_user&.has_role? :admin
    #   redirect_to admin_dashboard_path
    # else
      redirect_to products_path
    # end
  end

  def about
    @about = About&.last
  end

  def contact_us
    @contact = Contact.last
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light"><%= @about.title %> </h1>
      <p class="lead text-muted"><%= @about.content %></p>
      <p>
        <a href="<%= contact_us_path %>" class="btn btn-primary my-2">Contact us</a>
      </p>
    </div>
  </div>
</section>

app/views/home/contact_us.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light"><%= @contact.title %> </h1>
      <p class="lead text-muted"><%= @contact.content %></p>
      <p>
        <a href="#" class="btn btn-primary my-2">Contact us</a>
      </p>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<h1>Welcome to TurboTech Parts</h1>