config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, only: [:index, :show]
  resource :cart, only: [:show]
  resources :orders, only: [:create, :update, :destroy]
  post '/orders/:id',  to: 'orders#create', as: "order_items"
  post '/orders/:id',  to: 'orders#update', as: "order_item"
  get '/category/:id',  to: 'product_categories#show', as: "category"
  get '/about',  to: 'home#about', as: "about"
  get '/contact_us',  to: 'home#contact_us', as: "contact_us"
  get '/orders/checkout', to: 'orders#checkout', as: "checkout"
  get '/order/placed', to: 'orders#post_checkout', as: "post_checkout"
  get 'all_products', to: 'products#all_products', as: "all_products"
  get 'featured_products', to: 'products#featured_products', as: "featured_products"
  get 'recent_products', to: 'products#recent_products', as: "recent_products"
  resources :payments
  root "home#index"
end

app/models/about.rb
class About < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "title", "updated_at"]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["content", "created_at", "id", "title", "updated_at"]
      end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  # validate :user_present
  enum status: { new: 0, paid: 1, shipped: 2, cancelled: 3 }, _prefix: :type
  enum payment_method: { cash_on_delivery: 0, online_payment: 1 }

  private

  def user_present
    if user_id.nil?
      errors.add(:user, "is necessary.")
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "delivery_charges", "id", "payment_method", "status", "total", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["order_items", "user"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  # belongs_to :order
  # validate :product_necessary
  # validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  # validate :order_necessary

  before_save :calculate_total_amount
  after_save :update_order

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "order_id", "price", "product_id", "quantity", "updated_at"]
  end
  private

  def order_necessary
    if order_id.nil?
      errors.add(:order, "is necessary.")
    end
  end
  def product_necessary
    if product_id.nil?
      errors.add(:product, "is necessary.")
    end
  end

  def calculate_total_amount
    self.total_amount = quantity.to_f * price.to_f
  end

  def update_order
    order = Order.find_by(id: self.order_id)
    order.total = order.order_items.sum(:total_amount)
    order.save!
  end

end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ProductImageUploader
  belongs_to :product_category
  has_many :order_items

  validate :product_category_present

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  scope :recent_products, -> { where("products.updated_at >= ?", 3.days.ago) }
  scope :featured_products, -> { where(is_featured: true) }

  # validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "name", "price", "product_category_id", "quantity", "updated_at"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["order_items", "product_category"]
  end
  private

  def product_category_present
    if product_category.nil?
      errors.add(:product_category, "is necessary.")
    end
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "name", "updated_at"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :resource, polymorphic: true, optional: true
  validates :resource_type, inclusion: { in: Rolify.resource_types }, allow_nil: true

  has_many :user_roles
  has_many :users, through: :user_roles

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :user_roles
  has_many :roles, through: :user_roles

  rolify

  after_commit :assign_default_role, on: :create

  private

  def assign_default_role
    if self.roles.blank?
      self.add_role(:customer)
    end
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  helper_method :current_order
  before_action :assign_categories

  def current_order
    if session[:order_id].nil?
      Order.new
    else
      begin
        Order.find_by(id: session[:order_id])
      rescue ActiveRecord::RecordNotFound => e
        Order.new
      end
    end
  end

  private

  def assign_categories
    @categories = ProductCategory.where("product_categories.name is not null")
  end
end

app/controllers/carts_controller.rb
class CartsController < BaseController

  add_breadcrumb "home", :root_path
  def show
    add_breadcrumb "products", products_path

    @order = current_order
    @order_items = current_order&.order_items
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # if current_user&.has_role? :admin
    #   redirect_to admin_dashboard_path
    # else
      redirect_to products_path
    # end
  end

  def about
    @about = About&.last
  end

  def contact_us
    @contact = Contact.last
  end

end

app/controllers/orders_controller.rb
class OrdersController < BaseController
  def create
    @order_item = OrderItem.where("product_id = ? AND order_id = ?", params[:order_item][:product_id], session[:order_id]).first
    if @order_item
      @order_item.update(quantity: @order_item.quantity + params[:order_item][:quantity].to_i)
      @order_item.save
    else
      @order = current_order
      @order.user = current_user.present? ? current_user : User.last
      @order.order_items.new(order_item_params)
      @order.save
      session[:order_id] = @order.id
    end
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find_by(id: params[:id])
    @order_item.update(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find_by(id: params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

  def checkout
    if !current_user
      redirect_to new_user_session_path
    elsif params["payment_method"] == "0"
      current_order.update(address: params["address"], payment_method: params["payment_method"].to_i, user_id: current_user.id, status: 0)
      redirect_to post_checkout_path
    else
      redirect_to new_payment_path
    end
  end

  def post_checkout
    @order = current_order
    session[:order_id] = nil
  end

  private

  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id, :price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_auth.html.erb
<% if user_signed_in? %>
  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <%= link_to current_user.email, "#", class: "nav-link dropdown-toggle", role: "button", "data-bs-toggle": "dropdown" %>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete }, :class => 'dropdown-item' %>
        <%= link_to "Edit User", edit_user_registration_path, data: { "turbo-method": :get }, :class => 'dropdown-item' %>
      </div>
    </li>
  </ul>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary mx-1", role: "button" %>
  <%= link_to "Login", new_user_session_path, class: "btn btn-primary", role: "button" %>
<% end %>

app/views/layouts/_cart.html.erb
<div class="cart-text">
  <%= link_to cart_path, class: "btn btn-outline-dark" do %>
    </i><i class="bi bi-cart4"></i>
    <% if current_order.present? %>
      <%= current_order.order_items.size %>  Products in Cart  <%= number_to_currency current_order.total %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
  <div class="container-fluid">
    <%= link_to "TurboTech Parts", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item dropdown">

          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% @categories&.each do |cat| %>
              <%= link_to cat.name.capitalize, category_path(cat), class: "dropdown-item" %>
            <% end %>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/featured_products">Feature Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/recent_products">Recent Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/all_products">All Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">About TurboTech Parts</a>
        </li>
        <l1 class="nav-item">
          <%= form_tag all_products_path, :method => "get", :class => "form-inline" do %>
            <%=  text_field_tag :search, params[:search], class: "form-control mr-sm-2", placeholder: "Product Name?" %>
              <%= submit_tag("Search", :name=>nil) %>
            <% end %>
        </l1>
      </ul>
      <form class="d-flex">
        <%= render 'layouts/cart' %>
        <%= render 'layouts/auth' %>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboTech Parts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/header" if controller_name == "orders" || controller_name == "products" || controller_name == "home" || controller_name == "product_categories" || controller_name == "carts" || controller_name == "payments"  %>
  <p class="notice"><%= notice %></p>

  <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>